[project]
name = "democratizing-ai-compute"
version = "0.1.0"
description = "Experiments from Democratizing AI Compute: https://www.modular.com/democratizing-ai-compute"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cupy-cuda13x>=14.1.1",
    "jupyter>=1.1.1",
    "max[all]>=26.6.0.dev2026081605",
    "nvmath-python[cu13,numba]>=1.0.0",
]

[[tool.uv.index]]
url = "https://whl.modular.com/nightly/simple/"
